services:
  fastapi:
    build: .
    container_name: data-collection-service
    ports:
      - "8000:8000"
    depends_on:
      - kafka
      - redis

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery-worker
    command: ["celery", "-A", "scheduler.task", "worker", "--loglevel=INFO"]
    depends_on:
      - redis
      - kafka
